
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `portal_resume_job_match` DISABLE KEYS */;
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (1,6,1,1,5,'poor',NULL,'Java','{\"skillMatch\": {\"score\": 0, \"suggestions\": [\"补充Java基础、面向对象、集合、并发等技能\", \"补充常用Java生态技术，如Spring、Spring Boot、MySQL、Git等\"]}, \"keywordMatch\": {\"score\": 0, \"suggestions\": [\"在技能、项目或工作经历中明确补充Java相关关键词\", \"围绕Java工程师岗位增加后端开发相关术语\"]}, \"structureMatch\": {\"score\": 10, \"suggestions\": [\"补充电话、求职意向、教育经历、工作经历、项目经历、技能列表和自我介绍\", \"完善简历各模块内容，形成完整可评估的求职材料\"]}, \"experienceMatch\": {\"score\": 0, \"suggestions\": [\"补充Java相关工作经历或实习经历\", \"补充可体现Java开发能力的项目经历\"]}}','候选人简历除姓名和邮箱外几乎为空，未体现任何Java技能、项目或工作经验，与Java工程师岗位匹配度极低。建议优先补充求职意向、教育经历、Java相关技能与项目/工作经历，并增加可量化的成果描述。',1,'2026-08-31 10:37:49');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (2,6,1,2,3,'poor',NULL,'Java、后端框架、HTML、CSS、JavaScript、Vue、MySQL、数据库优化、微服务、系统架构、Web应用、高可用、代码审查、敏捷开发、沟通协作、独立解决问题、学习能力、本科、视觉算法、深度学习','{\"skillMatch\": {\"score\": 0, \"suggestions\": [\"技能列表为空，无法评估岗位所需技术能力\", \"建议补充Java及后端框架、前端Vue、MySQL、微服务架构等技能\", \"如有敏捷开发、团队协作、独立排障等软技能，也应具体说明\"]}, \"keywordMatch\": {\"score\": 0, \"suggestions\": [\"简历未体现Java、后端框架、前端技术等岗位核心关键词\", \"如有相关技术基础，应补充HTML、CSS、JavaScript、Vue、MySQL等关键词\", \"若有视觉算法或深度学习经验，应单独明确写出\"]}, \"structureMatch\": {\"score\": 8, \"suggestions\": [\"简历仅有姓名和邮箱，电话等基础信息不完整\", \"缺少教育经历、求职意向、工作经历、项目经历、技能列表和自我介绍\", \"建议按目标岗位补齐核心模块，并量化描述项目成果\"]}, \"experienceMatch\": {\"score\": 0, \"suggestions\": [\"简历缺少工作经历、项目经历，无法判断Web应用开发经验\", \"建议补充全栈开发、系统架构、数据库设计、微服务等实际项目经验\", \"可补充高可用、性能优化、代码审查、故障排查等职责相关经验\"]}}','候选人简历信息严重不足，未体现全栈工程师所需的Java、前端、数据库、微服务和项目经验，当前与岗位匹配度很低。建议优先补齐教育、工作、项目、技能等模块，并围绕Java、Vue、MySQL、Web应用和高可用开发进行针对性描述。',1,'2026-09-01 09:05:20');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (3,6,1,2,3,'poor',NULL,'Java、后端框架、HTML、CSS、JavaScript、Vue、MySQL、数据库优化、微服务架构、Web应用开发、系统架构设计、代码审查、高可用、团队协作、敏捷开发、独立解决问题、学习能力、本科及以上、深度学习、视觉算法','{\"skillMatch\": {\"score\": 0, \"suggestions\": [\"技能列表为空，无法证明Java、Vue、MySQL、微服务等岗位所需能力。\", \"建议按后端、前端、数据库、架构与工程能力分类补充技能，并标注熟练程度。\"]}, \"keywordMatch\": {\"score\": 0, \"suggestions\": [\"简历中未出现Java、后端框架、前端技术、数据库、微服务等岗位核心关键词。\", \"建议在技能、项目和工作经历中明确写出与全栈工程师岗位相关的技术关键词。\"]}, \"structureMatch\": {\"score\": 10, \"suggestions\": [\"简历仅包含姓名和邮箱，教育经历、求职意向、工作经历、项目经历、技能列表和自我介绍均缺失。\", \"建议先补齐基础简历模块，再针对目标岗位进行内容优化。\"]}, \"experienceMatch\": {\"score\": 0, \"suggestions\": [\"未填写工作经历和项目经历，无法评估Web应用开发、系统架构、数据库设计等经验。\", \"建议补充完整项目背景、个人职责、技术栈和可量化成果。\"]}}','候选人与全栈工程师岗位当前匹配度极低，简历缺少教育、工作、项目、技能和自我介绍等关键信息，无法证明Java、前端、数据库及全栈开发能力。建议优先补齐简历核心模块，并围绕Java后端、Vue前端、MySQL、微服务和Web应用开发要求补充可验证的项目成果。',1,'2026-09-01 09:48:41');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (4,6,1,2,60,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库设计与优化、后端开发、前端开发、接口设计、代码评审、敏捷开发、与产品协作、与UI/UX协作、系统故障排查、高可用优化','本科及以上学历、计算机或软件工程专业、视觉算法、深度学习、项目经历、工作经历、高性能架构、系统架构设计、完整开发生命周期、独立解决复杂问题','{\"skillMatch\": {\"score\": 82, \"suggestions\": [\"补充Spring Boot、MySQL、Vue等技能的具体使用场景或版本信息\", \"增加微服务落地细节，如服务拆分、网关、注册中心、链路追踪等\", \"补充测试、部署、CI/CD、性能优化等工程化能力\"]}, \"keywordMatch\": {\"score\": 80, \"suggestions\": [\"补充视觉算法或深度学习相关关键词\", \"明确本科及以上学历及计算机、软件工程专业背景\", \"增加高性能、可扩展、高可用等架构类关键词\"]}, \"structureMatch\": {\"score\": 22, \"suggestions\": [\"补全电话、求职意向、期望城市、期望薪资等基本信息\", \"补充教育经历，明确学历和专业\", \"补充工作经历、项目经历模块，形成完整简历结构\"]}, \"experienceMatch\": {\"score\": 30, \"suggestions\": [\"补充完整工作经历与项目经历，验证全栈开发经验\", \"将自我介绍中的[X]年、[X%]替换为真实量化数据\", \"补充具体业务场景、职责分工和交付成果\"]}}','候选人技术栈与全栈工程师岗位核心要求较匹配，覆盖Java、Spring Boot、MySQL、Vue、微服务等关键能力。但简历缺少教育经历、工作经历和项目经历，且存在占位符，难以充分验证真实经验、架构能力和交付成果。建议补全项目案例、学历信息、量化指标，并补充视觉算法或深度学习相关经历以提升竞争力。',1,'2026-09-01 09:52:26');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (5,6,1,2,55,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库优化、代码评审、敏捷协作、故障定位','视觉算法、深度学习、本科及以上学历、系统架构设计、高性能优化、Web应用安全、项目经历、工作经历','{\"skillMatch\": {\"score\": 75, \"suggestions\": [\"已有Java/Spring Boot/MySQL/Vue等核心技能，建议用项目成果佐证熟练度\", \"补充前端工程化、接口规范、性能压测、安全实践等技能细节\", \"若有深度学习/视觉算法相关实践，单独列出技术栈与应用场景\"]}, \"keywordMatch\": {\"score\": 72, \"suggestions\": [\"补充视觉算法、深度学习等优先项关键词（如有）\", \"在经历中体现系统架构设计、高性能、安全、稳定性等岗位关键词\", \"将[X]年、[X%]等占位符替换为真实量化数据\"]}, \"structureMatch\": {\"score\": 20, \"suggestions\": [\"补全电话、求职意向、教育经历、工作经历、项目经历等关键模块\", \"为每段经历添加背景、职责、技术栈和量化成果\", \"删除占位符内容，形成可验证的完整简历\"]}, \"experienceMatch\": {\"score\": 25, \"suggestions\": [\"补充完整工作经历与项目经历，证明Java Web与全栈开发经验\", \"提供数据库设计、微服务拆分、接口设计、故障优化的具体案例和结果\", \"补充学历信息以满足本科及以上要求\"]}}','候选人技能栈与全栈工程师岗位核心要求较匹配，覆盖Java、Spring Boot、MySQL、Vue、微服务和数据库优化等关键点。但简历缺少教育、工作/项目经历及量化成果，经验可信度和结构完整度明显不足。建议补齐学历与项目经历，突出系统架构、性能优化、高可用与安全实践，并补充视觉算法/深度学习相关加分项。',1,'2026-09-01 10:39:00');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (6,6,1,2,45,'poor','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库优化、代码评审、敏捷协作、故障定位','视觉算法、深度学习、项目经历、工作经历、本科及以上学历、系统架构设计、高性能优化、量化成果','{\"skillMatch\": {\"score\": 70, \"suggestions\": [\"现有Java、Spring Boot、Vue、MySQL、微服务技能与岗位匹配，但需通过项目证明熟练度。\", \"补充前后端工程化、部署运维、安全与性能相关技能。\", \"如有视觉算法或深度学习技术栈，请补充；否则可弱化优先项。\"]}, \"keywordMatch\": {\"score\": 75, \"suggestions\": [\"补充视觉算法、深度学习等优先项关键词，若有相关经验需明确写出。\", \"将技能关键词与具体项目结合，避免仅有技能列表。\", \"用量化指标强化高可用、性能优化等关键词。\"]}, \"structureMatch\": {\"score\": 15, \"suggestions\": [\"补全电话、求职意向、教育经历、工作经历、项目经历等必填模块。\", \"移除自我介绍中的[X]占位符，使用真实年限和量化结果。\", \"增加项目描述中的背景、职责、技术方案和成果。\"]}, \"experienceMatch\": {\"score\": 20, \"suggestions\": [\"补充完整工作经历与项目经历，明确Java全栈开发年限、业务规模和职责。\", \"提供系统架构设计、微服务落地、数据库优化的实际案例。\", \"补充教育经历以满足本科及以上要求。\"]}}','候选人技能关键词与全栈岗位较匹配，覆盖Java、Spring Boot、Vue、MySQL和微服务等核心要求。但简历缺少教育、工作、项目经历及量化成果，无法证明岗位所需的丰富经验、架构能力和高可用交付能力。建议补全经历与项目案例，并补充视觉算法或深度学习相关经验。',1,'2026-09-01 10:39:57');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (7,6,1,2,56,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库设计、查询优化、代码评审、敏捷协作、系统故障处理','视觉算法、深度学习、本科及以上学历、项目经历、工作经历、高可用架构、性能优化量化','{\"skillMatch\": {\"score\": 82, \"suggestions\": [\"技能栈与岗位要求较匹配，覆盖后端、前端、数据库和微服务\", \"建议补充Spring Boot、Vue、MySQL、微服务在实际项目中的应用场景\", \"如有视觉算法、深度学习相关技术栈，应单独列出以提升岗位匹配度\"]}, \"keywordMatch\": {\"score\": 72, \"suggestions\": [\"简历已覆盖Java、Spring Boot、MySQL、Vue、微服务等核心关键词\", \"缺少视觉算法、深度学习等加分项关键词，若有相关经验建议补充\", \"建议补充高可用、可扩展架构、性能优化等岗位关键词的具体描述\"]}, \"structureMatch\": {\"score\": 25, \"suggestions\": [\"教育经历、工作经历、项目经历均为空，简历完整度不足\", \"缺少电话、求职意向等基础信息，影响招聘方联系和岗位匹配判断\", \"建议补全基本信息、教育背景、工作/项目经历，并增加可量化的成果描述\"]}, \"experienceMatch\": {\"score\": 30, \"suggestions\": [\"简历未填写工作经历和项目经历，无法验证全栈开发经验的真实性与深度\", \"自我介绍中存在[X]年、[X%]等占位符，需替换为真实年限和量化结果\", \"建议补充Web应用开发、微服务拆分、数据库优化、故障处理相关项目案例\"]}}','候选人技能栈与全栈工程师岗位较匹配，覆盖Java、Spring Boot、MySQL、Vue和微服务等核心要求，但简历缺少教育经历、工作/项目经历及量化成果，经验可信度不足。建议补全项目经历和工作经历，明确开发年限、性能优化和高可用成果，并补充视觉算法或深度学习相关经验以提升匹配度。',1,'2026-09-01 10:41:05');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (8,6,1,2,58,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务、数据库优化、代码评审、敏捷开发、系统故障定位、高可用、跨团队协作','视觉算法、深度学习、系统架构设计、完整项目经历、本科及以上学历、性能优化成果','{\"skillMatch\": {\"score\": 82, \"suggestions\": [\"补充Spring Boot、微服务相关组件与部署运维能力\", \"补充Vue项目中的组件化、状态管理或前端工程化实践\", \"说明数据库设计、SQL优化、代码评审的具体案例\"]}, \"keywordMatch\": {\"score\": 78, \"suggestions\": [\"补充视觉算法、深度学习等岗位优先项关键词\", \"增加系统架构设计、完整开发生命周期等职责关键词\", \"将微服务、数据库优化、高可用等关键词与具体项目场景结合\"]}, \"structureMatch\": {\"score\": 25, \"suggestions\": [\"补齐手机号、求职意向、教育经历和工作经历\", \"增加项目经历模块并按STAR方式描述\", \"将自我介绍中的占位符替换为真实年限和数据\"]}, \"experienceMatch\": {\"score\": 30, \"suggestions\": [\"补充至少2-3个完整项目或工作经历\", \"说明项目规模、个人职责、技术栈和交付结果\", \"量化系统故障处理、高可用保障和性能优化成果\"]}}','候选人在Java、Spring Boot、MySQL、Vue和微服务等全栈核心技术上覆盖较高，但简历缺少教育、工作/项目经历与量化成果，难以充分验证真实经验深度。建议补全项目职责、系统架构设计和高可用/性能优化成果，并明确学历及视觉算法/深度学习相关经历。',1,'2026-09-01 10:51:40');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (9,6,1,2,58,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库优化、前端开发、后端开发、敏捷开发、代码评审、团队协作','视觉算法、深度学习、系统架构设计、本科及以上、工作经历、项目经历','{\"skillMatch\": {\"score\": 78, \"suggestions\": [\"现有Java、Spring Boot、MySQL、Vue等技能与岗位匹配度较高\", \"可补充视觉算法或深度学习相关技能，提升岗位加分项\"]}, \"keywordMatch\": {\"score\": 80, \"suggestions\": [\"补充视觉算法、深度学习等岗位优先项相关关键词\", \"增加系统架构设计、高性能优化、高可用保障等职责关键词\"]}, \"structureMatch\": {\"score\": 20, \"suggestions\": [\"补充教育经历、工作经历、项目经历和求职意向\", \"完善联系电话并将自我介绍中的占位符替换为真实量化数据\"]}, \"experienceMatch\": {\"score\": 30, \"suggestions\": [\"补充完整工作经历和项目经历，证明全栈开发经验\", \"用具体案例说明数据库优化、微服务拆分、故障排查和高可用成果\"]}}','候选人具备Java、Spring Boot、MySQL、Vue等全栈岗位核心技能，关键词覆盖较好，但简历缺少教育、工作、项目经历等关键证明材料，难以充分体现经验丰富的高级全栈要求。建议补全履历并量化系统架构、性能优化和高可用成果，同时补充视觉算法或深度学习相关经验以增强竞争力。',1,'2026-09-01 10:52:02');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (10,6,1,2,42,'poor','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库优化、代码评审、系统故障排查、敏捷开发','视觉算法、深度学习、项目经历、工作经历、高可用架构、性能优化、系统架构设计、本科学历','{\"skillMatch\": {\"score\": 74, \"suggestions\": [\"技能栈与岗位核心要求较匹配，但缺少技能在项目中的应用证据。\", \"建议补充Spring Boot、微服务组件、Vue页面开发、MySQL索引优化、接口设计等具体实践。\", \"若具备代码审查、CI/CD、测试、部署或视觉算法相关经验，应单独列出以增强竞争力。\"]}, \"keywordMatch\": {\"score\": 80, \"suggestions\": [\"已覆盖Java、前端、MySQL、微服务等核心关键词，建议在项目或工作经历中进一步用实例证明这些能力。\", \"如有视觉算法或深度学习经验，应补充相关关键词与项目成果；如无，可减少无关预期。\", \"将自我介绍中的占位符替换为真实年限、指标和业务场景，提高关键词可信度。\"]}, \"structureMatch\": {\"score\": 12, \"suggestions\": [\"教育经历、工作经历、项目经历和求职意向均缺失，简历完整度较低。\", \"补充电话、期望职位、期望城市、教育背景等基础信息，便于招聘方判断基本匹配。\", \"使用结构化表达呈现项目经历，如项目背景、职责、技术栈、难点、成果和量化指标。\"]}, \"experienceMatch\": {\"score\": 12, \"suggestions\": [\"简历缺少工作经历和项目经历，无法验证全栈工程师所需的完整开发生命周期经验。\", \"补充至少2-3个Web应用项目，说明架构设计、后端开发、前端实现、数据库优化和上线效果。\", \"增加高可用、高性能、故障排查和微服务落地的量化案例，例如QPS、响应时间、可用性提升等。\"]}}','候选人在Java、Spring Boot、MySQL、Vue和微服务等核心技能关键词上与全栈工程师岗位有较高匹配度，但缺少教育、工作、项目和量化成果支撑，难以证明岗位要求的丰富实战经验。建议补齐完整简历结构，重点增加Web全栈项目经历、性能优化与高可用案例。若有视觉算法或深度学习经验，应明确突出；若无，则应聚焦工程能力证明。',1,'2026-09-01 14:33:36');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (11,6,1,2,55,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库优化、代码评审、敏捷开发、团队协作','视觉算法、深度学习、本科及以上、工作经历、项目经历、系统架构设计、高性能优化案例、可量化成果','{\"skillMatch\": {\"score\": 76, \"suggestions\": [\"当前后端与前端技能与岗位较匹配，建议补充实际项目作品佐证\", \"若有视觉算法或深度学习相关实践，应单独列出\", \"补充架构设计、安全设计、性能调优相关能力证据\"]}, \"keywordMatch\": {\"score\": 78, \"suggestions\": [\"补充视觉算法、深度学习等岗位优先项关键词\", \"增加系统架构设计、高性能、安全性等JD核心词\", \"将微服务拆分、数据库优化等关键词放入具体项目描述中增强可信度\"]}, \"structureMatch\": {\"score\": 22, \"suggestions\": [\"补齐电话、求职意向、教育经历、工作经历和项目经历\", \"使用STAR格式描述项目背景、职责、技术方案和业务成果\", \"完善简历基本结构，提高招聘方可读性和可信度\"]}, \"experienceMatch\": {\"score\": 28, \"suggestions\": [\"补充完整工作经历和项目经历，证明实际参与过Web应用全生命周期开发\", \"提供高可用、故障定位、性能优化的量化成果\", \"避免使用[X]类占位符，明确工作年限与项目指标\"]}}','候选人在Java、Spring Boot、Vue、MySQL、微服务等核心技能上与全栈工程师岗位匹配度较高，但简历缺少教育经历、工作经历、项目经历和量化成果，难以充分验证真实工程能力。建议补齐项目与工作经历，并增加视觉算法、深度学习等岗位加分项，以提升整体竞争力。',1,'2026-09-01 15:50:15');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (12,6,1,2,68,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、前后端开发、接口设计、数据库设计、代码评审、敏捷协作、系统故障定位','本科及以上学历、系统架构设计、可扩展解决方案、安全与稳定性、视觉算法、深度学习','{\"skillMatch\": {\"score\": 86, \"suggestions\": [\"Java、Spring Boot、MySQL、Vue、HTML/CSS/JavaScript与岗位核心技能匹配度较高\", \"可进一步补充系统设计、服务治理、性能调优、安全开发相关能力\", \"如有视觉算法或深度学习相关技术经历，应单独列出以匹配岗位优先项\"]}, \"keywordMatch\": {\"score\": 84, \"suggestions\": [\"已覆盖Java、Spring Boot、MySQL、Vue、前端基础和微服务等核心关键词\", \"补充岗位优先项关键词，如视觉算法、深度学习\", \"将工作经历中的[X]占位符替换为真实数据，提升关键词可信度\"]}, \"structureMatch\": {\"score\": 35, \"suggestions\": [\"基本信息缺少电话，求职意向未填写，影响简历完整度\", \"教育经历字段为空且描述无效，需补充学校、专业、学历和时间\", \"项目经历描述过于简单且含测试文字，应改写为背景、职责、技术栈和成果\", \"删除[X]、[X%]等占位符，替换为真实可量化的结果\"]}, \"experienceMatch\": {\"score\": 58, \"suggestions\": [\"具备Java后端与Vue前端协同开发经历，方向与全栈岗位相关\", \"缺少可验证的项目规模、用户量、性能指标和高可用成果\", \"教育经历未体现本科及以上要求，且时间信息异常，需要补齐真实学历背景\", \"建议补充架构设计、性能优化、故障治理等更具资深全栈工程师特征的实践\"]}}','候选人在Java全栈技术栈上与岗位高度相关，覆盖Spring Boot、MySQL、Vue、微服务和前后端协作开发。但简历中教育信息缺失、项目描述不规范、多处占位符和时间异常，削弱了经验真实性与资深程度。建议补齐学历和量化项目成果，并增强架构设计、高可用及视觉算法/深度学习等加分项。',1,'2026-09-01 15:57:53');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (13,6,1,2,62,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、数据库优化、代码评审、敏捷协作、故障定位','视觉算法、深度学习、本科及以上学历、计算机相关专业、高性能架构设计、独立解决复杂问题','{\"skillMatch\": {\"score\": 80, \"suggestions\": [\"增加微服务治理、数据库调优、前端工程化等技能的具体实践证据\", \"若有视觉算法或深度学习经验，补充相关模型、框架和应用场景\"]}, \"keywordMatch\": {\"score\": 78, \"suggestions\": [\"保留并前置 Java、Spring Boot、MySQL、Vue 等岗位核心关键词\", \"如有相关经验，补充视觉算法、深度学习等优先项关键词\"]}, \"structureMatch\": {\"score\": 35, \"suggestions\": [\"补全电话、求职意向、教育经历等基础信息，删除乱码和无效描述\", \"按 STAR 结构重写工作经历和项目经历，明确时间线、角色、成果\"]}, \"experienceMatch\": {\"score\": 55, \"suggestions\": [\"补充可验证的全栈项目背景、业务规模、个人职责和上线结果\", \"量化高性能、可扩展、高可用相关成果，替换 [X]、[X%] 等占位符\"]}}','候选人技术栈与全栈工程师岗位较为匹配，覆盖 Java、Spring Boot、MySQL、Vue 和微服务等核心要求，但简历信息完整性较差，项目与教育经历缺少有效支撑，难以证明资深交付能力。建议补全学历、项目细节和量化成果，并补充视觉算法、深度学习等加分项经历。',1,'2026-09-02 10:22:53');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (14,6,1,2,68,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、SQL查询优化、接口设计、前后端联调、代码审查、敏捷开发、高可用、系统架构设计','本科及以上学历、深度学习、视觉算法、性能优化、系统安全性','{\"skillMatch\": {\"score\": 82, \"suggestions\": [\"突出微服务拆分、服务治理、缓存、消息队列等后端深度能力\", \"补充前端工程化、组件化、复杂交互或性能优化细节\"]}, \"keywordMatch\": {\"score\": 80, \"suggestions\": [\"补充视觉算法、深度学习等岗位优先关键词\", \"增加性能优化、安全设计、高可用治理等结果型关键词\"]}, \"structureMatch\": {\"score\": 40, \"suggestions\": [\"删除占位符，补全学校、专业、学历、项目职责和链接\", \"使用STAR结构完善项目背景、职责、指标和成果\"]}, \"experienceMatch\": {\"score\": 58, \"suggestions\": [\"补全真实工作经历、项目时间线和教育经历\", \"补充可量化的业务成果、故障处理和系统优化案例\"]}}','候选人技术栈与全栈工程师岗位高度相关，覆盖Java、Spring Boot、MySQL、Vue和微服务等核心要求。但简历存在明显占位符，学历、项目细节与量化成果不足，削弱经验可信度。建议补全教育经历与真实项目数据，并补充性能优化、安全、高可用及视觉算法/深度学习相关说明。',1,'2026-09-02 10:31:24');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (15,6,1,2,68,'medium','Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、SQL优化、前后端联调、代码审查、敏捷协作','视觉算法、深度学习、系统架构设计、数据库模型设计、本科及以上学历信息、量化项目成果','{\"skillMatch\": {\"score\": 78, \"suggestions\": [\"补充高性能、可扩展性、安全性和高可用方面的落地证据。\", \"若有视觉算法或深度学习实践，建议以项目形式呈现。\"]}, \"keywordMatch\": {\"score\": 82, \"suggestions\": [\"补充视觉算法或深度学习相关关键词与经历，贴合岗位优先项。\", \"在简历中明确系统架构设计、数据库模型设计等JD核心关键词。\"]}, \"structureMatch\": {\"score\": 48, \"suggestions\": [\"删除模板占位内容，补全教育经历、学校、专业、学历和时间。\", \"用STAR方式重写项目经历，增加量化指标和可验证链接。\"]}, \"experienceMatch\": {\"score\": 60, \"suggestions\": [\"补全工作经历与项目经历的真实职责、周期和成果，避免占位符。\", \"围绕Web应用开发、前后端协作和故障处理提供具体案例。\"]}}','候选人在Java、Spring Boot、MySQL、Vue和微服务等核心技术栈上与全栈工程师岗位高度匹配，但简历模板化严重，教育、项目和量化成果信息不足。建议补全真实经历与学历信息，并强化架构设计、高可用及视觉算法/深度学习相关证明。',1,'2026-09-02 10:31:56');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (16,6,1,2,66,'medium','全栈工程师、Java、Spring Boot、MySQL、Vue、HTML、CSS、JavaScript、微服务架构、SQL查询优化、接口设计、前后端联调、产品与UI协作、代码审查、高可用','本科及以上学历、视觉算法、深度学习、数据库模型设计、微服务项目经验','{\"skillMatch\": {\"score\": 82, \"suggestions\": [\"补充系统架构设计、性能优化和复杂问题处理案例\", \"补充数据库模型设计与查询优化的具体成果\", \"如有视觉算法或深度学习项目，建议单独说明\"]}, \"keywordMatch\": {\"score\": 80, \"suggestions\": [\"补充本科及以上学历、计算机相关专业等硬性关键词\", \"如具备相关经验，补充视觉算法、深度学习关键词\", \"将微服务架构进一步落到具体项目经验与成果中\"]}, \"structureMatch\": {\"score\": 45, \"suggestions\": [\"删除[X]、[学校]、[专业]等模板占位符\", \"完善教育经历、工作经历和项目经历的时间线\", \"增加项目链接、量化指标和可验证成果\"]}, \"experienceMatch\": {\"score\": 55, \"suggestions\": [\"补全教育经历，避免空白或模板化内容\", \"补充真实项目背景、职责与上线成果，减少占位符\", \"提供高可用、数据库优化、微服务相关的具体实践案例\"]}}','候选人技术栈与全栈Java岗位较匹配，覆盖Java、Spring Boot、MySQL、Vue、微服务和前后端协作等核心能力。但简历模板化明显，教育背景、项目细节、量化成果缺失，且视觉算法、深度学习和本科信息等要求未体现。建议补全真实项目、学历信息、数据库设计与高可用成果，以提升可信度和岗位匹配度。',1,'2026-09-02 10:32:59');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (17,6,6,2,42,'poor','Java、MySQL、JavaScript、Vue、Go、Python','微服务、至少一种后端语言、微服务架构、架构设计、HTML、关系型数据库','{\"skillMatch\": {\"score\": 50, \"suggestions\": []}, \"keywordMatch\": {\"score\": 50, \"suggestions\": [\"补充缺失关键词相关经验：微服务、至少一种后端语言、微服务架构、架构设计、HTML\"]}, \"structureMatch\": {\"score\": 29, \"suggestions\": []}, \"experienceMatch\": {\"score\": 60, \"suggestions\": []}}','基于JD关键词与简历结构的基础分析：关键词覆盖 6/12，结构完整度 29%。启用 AI 模型后可获得更精准的四维分析。',0,'2026-09-15 10:37:46');
INSERT INTO `portal_resume_job_match` (`id`, `user_id`, `resume_id`, `job_target_id`, `match_score`, `grade`, `matched_keywords`, `missing_keywords`, `dimensions`, `summary`, `ai_powered`, `create_time`) VALUES (18,6,6,2,85,'excellent','Java、微服务、MySQL、JavaScript、Vue、Go、架构设计、HTML、Python','至少一种后端语言、微服务架构、关系型数据库','{\"skillMatch\": {\"score\": 75, \"suggestions\": []}, \"keywordMatch\": {\"score\": 75, \"suggestions\": [\"补充缺失关键词相关经验：至少一种后端语言、微服务架构、关系型数据库\"]}, \"structureMatch\": {\"score\": 100, \"suggestions\": []}, \"experienceMatch\": {\"score\": 85, \"suggestions\": []}}','基于JD关键词与简历结构的基础分析：关键词覆盖 9/12，结构完整度 100%。启用 AI 模型后可获得更精准的四维分析。',0,'2026-09-16 14:29:01');
/*!40000 ALTER TABLE `portal_resume_job_match` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

