
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `portal_resume_optimize_task` DISABLE KEYS */;
INSERT INTO `portal_resume_optimize_task` (`id`, `user_id`, `resume_id`, `job_target_id`, `status`, `result_json`, `error_msg`, `ai_powered`, `create_time`, `start_time`, `finish_time`) VALUES (1,6,1,2,'success','{\"items\": [{\"field\": \"description\", \"index\": 0, \"reason\": \"补全求职意向并对齐全栈岗位。\", \"section\": \"objective\", \"original\": null, \"optimized\": \"求职意向：目标岗位Java全栈工程师，意向城市[城市]，工作类型[全职/远程]。面向Web应用全生命周期开发，聚焦高可用后端服务与Vue前端实现，愿意参与架构设计、数据库优化与代码评审，保障系统稳定性与用户体验。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"技能关键词精准匹配JD。\", \"section\": \"skills\", \"original\": \"\", \"optimized\": \"精通：Java、Spring Boot、MySQL\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、[视觉算法/深度学习]\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈、协作与高可用能力。\", \"section\": \"selfIntro\", \"original\": \"\", \"optimized\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"用STAR与量化占位补项目。\", \"section\": \"project\", \"original\": null, \"optimized\": \"[项目名称]：基于Java+Spring Boot+Vue的Web应用。职责：负责[模块]设计、接口开发、MySQL表结构优化与前端联调。行动：采用微服务/缓存/异步处理解决[问题]。结果：响应时间降低[X%]，并发能力提升[X%]，可用性达[X%]。\"}], \"summary\": \"围绕Java全栈岗位，优化求职意向、技能、自我介绍与项目模板，使用占位符避免编造。\", \"resumeId\": \"1\", \"aiPowered\": true, \"jobTargetId\": \"2\"}',NULL,1,'2026-09-01 09:49:13','2026-09-01 09:49:13','2026-09-01 09:50:25');
INSERT INTO `portal_resume_optimize_task` (`id`, `user_id`, `resume_id`, `job_target_id`, `status`, `result_json`, `error_msg`, `ai_powered`, `create_time`, `start_time`, `finish_time`) VALUES (2,6,1,2,'success','{\"items\": [{\"field\": \"description\", \"index\": 0, \"reason\": \"明确岗位与城市，匹配全栈招聘目标。\", \"section\": \"objective\", \"original\": null, \"optimized\": \"求职意向：全栈工程师/Java开发工程师；目标城市：[城市]；工作类型：全职；期望薪资：25-50K·15薪。围绕Web应用全生命周期开发，突出Java后端、MySQL优化、Vue前端协作与微服务实践，匹配高可用系统交付目标。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"对齐JD技术栈，体现前后端与微服务能力。\", \"section\": \"skills\", \"original\": \"Java(精通)、Spring Boot(精通)、MySQL(精通)、Vue(熟练)、HTML(熟练)、CSS(熟练)、JavaScript(熟练)、微服务架构(熟练)\", \"optimized\": \"精通：Java、Spring Boot、MySQL、微服务架构、RESTful接口设计、SQL查询优化、数据库模型设计、高可用Web服务开发。\\n熟练：Vue、HTML、CSS、JavaScript、敏捷协作、代码审查、Git、Maven、故障定位与性能优化。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"以量化占位符呈现成果，突出高可用能力。\", \"section\": \"selfIntro\", \"original\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]。\", \"optimized\": \"具备[X]年Java Web开发经验，参与需求分析、架构设计、后端接口开发、MySQL建模优化及Vue前端实现。曾支撑微服务模块上线，通过SQL优化与接口治理提升查询效率[X%]，保障可用性达[X%]。能与产品、UI/UX敏捷协作，主动定位系统故障并推动复盘。\"}], \"summary\": \"围绕全栈Java岗位强化意向、技能与自评，突出微服务、Vue与量化成果。\", \"resumeId\": \"1\", \"aiPowered\": true, \"jobTargetId\": \"2\"}',NULL,1,'2026-09-01 10:41:45','2026-09-01 10:41:45','2026-09-01 10:43:03');
INSERT INTO `portal_resume_optimize_task` (`id`, `user_id`, `resume_id`, `job_target_id`, `status`, `result_json`, `error_msg`, `ai_powered`, `create_time`, `start_time`, `finish_time`) VALUES (3,6,1,2,'success','{\"items\": [{\"field\": \"position\", \"index\": 0, \"reason\": \"对齐全栈岗位，补齐关键求职意向。\", \"section\": \"objective\", \"original\": \"\", \"optimized\": \"求职意向：全栈工程师/Java开发工程师，目标城市：[目标城市]，期望类型：全职。聚焦Java、Spring Boot、MySQL、Vue与微服务架构，参与Web应用设计、开发、维护及高质量交付。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"分层展示技能，匹配JD要求。\", \"section\": \"skills\", \"original\": \"Java(精通)、Spring Boot(精通)、MySQL(精通)、Vue(熟练)、HTML(熟练)、CSS(熟练)、JavaScript(熟练)、微服务架构(熟练)\", \"optimized\": \"精通：Java、Spring Boot、MySQL、接口设计、SQL查询优化、系统稳定性保障\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、代码评审、敏捷协作\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈交付与可用性量化。\", \"section\": \"selfIntro\", \"original\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]。\", \"optimized\": \"具备[X]年Java Web开发经验，参与后端服务、数据库模型设计与前端Vue页面开发。基于Spring Boot与MySQL完成接口开发、查询优化和微服务拆分，通过代码评审与故障定位提升系统稳定性，推动可用性优化至[X%]。能与产品、UI/UX敏捷协作，保障高质量交付。\"}], \"summary\": \"对齐全栈岗位，补齐意向并强化技能与稳定性量化。\", \"resumeId\": \"1\", \"aiPowered\": true, \"jobTargetId\": \"2\"}',NULL,1,'2026-09-01 10:52:08','2026-09-01 10:52:08','2026-09-01 10:53:37');
INSERT INTO `portal_resume_optimize_task` (`id`, `user_id`, `resume_id`, `job_target_id`, `status`, `result_json`, `error_msg`, `ai_powered`, `create_time`, `start_time`, `finish_time`) VALUES (4,6,1,2,'success','{\"items\": [{\"field\": \"position\", \"index\": 0, \"reason\": \"明确岗位匹配方向，补齐意向缺失。\", \"section\": \"objective\", \"original\": \"\", \"optimized\": \"全栈工程师（Java方向）；目标城市：[城市]；全职。期望负责Java后端、Vue前端与MySQL优化，参与微服务架构设计、代码评审及高可用Web应用交付，与产品、UI/UX协同推进敏捷迭代。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"分层呈现技能，贴合全栈要求。\", \"section\": \"skills\", \"original\": \"Java(精通)、Spring Boot(精通)、MySQL(精通)、Vue(熟练)、HTML(熟练)、CSS(熟练)、JavaScript(熟练)、微服务架构(熟练)\", \"optimized\": \"精通：Java、Spring Boot、MySQL、数据库设计与查询优化\\\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、敏捷开发协作\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈与故障优化能力。\", \"section\": \"selfIntro\", \"original\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]。\", \"optimized\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]，保障Web应用稳定、安全、高性能交付。\"}], \"summary\": \"围绕全栈岗位补全意向、技能分层与自我评价，突出Java、Vue与量化占位。\", \"resumeId\": \"1\", \"aiPowered\": true, \"jobTargetId\": \"2\"}',NULL,1,'2026-09-01 14:34:03','2026-09-01 14:34:03','2026-09-01 14:35:15');
/*!40000 ALTER TABLE `portal_resume_optimize_task` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

