
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `portal_resume_optimize_history` DISABLE KEYS */;
INSERT INTO `portal_resume_optimize_history` (`id`, `user_id`, `resume_id`, `from_resume_id`, `job_target_id`, `score_before`, `score_after`, `match_score_before`, `match_score_after`, `adopted_count`, `total_count`, `optimize_data`, `create_time`) VALUES (1,6,1,1,2,11,21,3,NULL,4,4,'{\"items\": [{\"field\": \"description\", \"index\": 0, \"reason\": \"补全求职意向并对齐全栈岗位。\", \"status\": \"adopted\", \"section\": \"objective\", \"original\": null, \"optimized\": \"求职意向：目标岗位Java全栈工程师，意向城市[城市]，工作类型[全职/远程]。面向Web应用全生命周期开发，聚焦高可用后端服务与Vue前端实现，愿意参与架构设计、数据库优化与代码评审，保障系统稳定性与用户体验。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"技能关键词精准匹配JD。\", \"status\": \"adopted\", \"section\": \"skills\", \"original\": \"\", \"optimized\": \"精通：Java、Spring Boot、MySQL\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、[视觉算法/深度学习]\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈、协作与高可用能力。\", \"status\": \"adopted\", \"section\": \"selfIntro\", \"original\": \"\", \"optimized\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"用STAR与量化占位补项目。\", \"status\": \"adopted\", \"section\": \"project\", \"original\": null, \"optimized\": \"[项目名称]：基于Java+Spring Boot+Vue的Web应用。职责：负责[模块]设计、接口开发、MySQL表结构优化与前端联调。行动：采用微服务/缓存/异步处理解决[问题]。结果：响应时间降低[X%]，并发能力提升[X%]，可用性达[X%]。\"}], \"summary\": \"围绕Java全栈岗位，优化求职意向、技能、自我介绍与项目模板，使用占位符避免编造。\"}','2026-09-01 09:51:07');
INSERT INTO `portal_resume_optimize_history` (`id`, `user_id`, `resume_id`, `from_resume_id`, `job_target_id`, `score_before`, `score_after`, `match_score_before`, `match_score_after`, `adopted_count`, `total_count`, `optimize_data`, `create_time`) VALUES (2,6,1,1,2,21,41,62,NULL,6,6,'{\"items\": [{\"field\": \"position\", \"index\": 0, \"reason\": \"明确目标岗位，匹配全栈与Java要求。\", \"status\": \"adopted\", \"section\": \"objective\", \"original\": \"\", \"optimized\": \"求职意向：全栈工程师 / Java后端开发工程师。聚焦Java、Spring Boot、MySQL、Vue与微服务架构方向，期望参与Web应用全生命周期开发、接口设计、前后端联调与高可用系统建设。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"教育信息缺失，需补齐关键信息。\", \"status\": \"adopted\", \"section\": \"education\", \"original\": \"阿萨v撒啊 俺的\", \"optimized\": \"学校/专业/学历/时间：[学校] · [专业] · [学历] · [起止时间]；主修课程：[课程]；荣誉奖项：[奖项]；若有深度学习、视觉算法或计算机相关项目，请补充项目名称、职责与成果。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈交付与量化结果。\", \"status\": \"adopted\", \"section\": \"work\", \"original\": \"\\n      负责基于 Java、Spring Boot、MySQL 与 Vue 的功能开发及接口联调，完成需求理解、编码实现、自测与文档沉淀；通过规范接口设计和复用公共组件，支撑 [X] 个模块上线，开发效率提升 [X%]，缺陷率下降 [X%]，累计沉淀技术文档 [X] 篇。\\n     突出 Java、Spring Boot、MySQL、Vue 和微服务相关技术栈，强化工程实现与文档规范性。\\n    基于微服务架构参与前后端功能开发，使用 Spring Boot 实现服务端接口，结合 MySQL 完成数据访问，并通过 Vue、HTML、CSS、JavaScript 构建页面交互；同步输出接口说明、实现方案与变更记录，提升代码可维护性与问题定位效率 [X%]。 \\n \\\"强调编码与文档对需求交付、协作效率及业务上线的支撑价值。\\n  围绕业务需求完成功能开发、页面实现与文档沉淀，将需求转化为可交付代码与可复用资料；通过整理接口说明、操作流程和变更记录，降低协作沟通成本 [X%]，支撑 [X] 个需求按期上线，提升业务响应效率 [X%]。\\n\", \"optimized\": \"负责基于Java、Spring Boot、MySQL、Vue与微服务架构的Web功能开发，参与需求评审、接口设计、编码实现、联调自测及文档沉淀；配合产品与UI/UX完成前后端集成，优化SQL查询与公共组件，支撑 [X] 个模块上线，开发效率提升 [X%]，缺陷率下降 [X%]，接口问题定位效率提升 [X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"重构乱码描述，补充真实项目价值。\", \"status\": \"adopted\", \"section\": \"project\", \"original\": \"阿斯顿v啊啊俺的啊\", \"optimized\": \"墨韵项目：围绕[业务场景]完成系统设计与功能实现，负责[前端页面/后端接口/数据库设计/联调测试]中的[具体职责]，使用[Java/Spring Boot/MySQL/Vue等真实技术]支撑[功能模块]交付，提升[业务指标/效率] [X%]，降低[问题率/成本] [X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"分层展示技能，匹配全栈要求。\", \"status\": \"adopted\", \"section\": \"skills\", \"original\": \"Java(精通)、Spring Boot(精通)、MySQL(精通)、Vue(熟练)、HTML(熟练)、CSS(熟练)、JavaScript(熟练)、微服务架构(熟练)\", \"optimized\": \"精通：Java、Spring Boot、MySQL、SQL查询优化、接口设计\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、前后端联调、代码文档沉淀\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"强化全栈、协作与稳定性保障。\", \"status\": \"adopted\", \"section\": \"selfIntro\", \"original\": \"具备[X]年Java Web开发经验，参与后端服务、数据库设计与前端Vue页面开发。熟悉微服务拆分、接口设计、MySQL查询优化与代码评审，能够与产品、UI/UX协作推进敏捷迭代。面对系统故障，能定位瓶颈并优化可用性至[X%]。\", \"optimized\": \"具备[X]年Java Web全栈开发经验，熟悉Spring Boot、MySQL、Vue、HTML/CSS/JavaScript及微服务架构。能够参与架构设计、数据库优化、接口评审、代码审查与敏捷协作，推动前后端高质量交付；面对系统故障可定位瓶颈并优化可用性至[X%]。\"}], \"summary\": \"围绕全栈岗位补齐意向、教育、工作、项目与技能，突出Java、Vue、MySQL与微服务。\"}','2026-09-02 10:29:31');
INSERT INTO `portal_resume_optimize_history` (`id`, `user_id`, `resume_id`, `from_resume_id`, `job_target_id`, `score_before`, `score_after`, `match_score_before`, `match_score_after`, `adopted_count`, `total_count`, `optimize_data`, `create_time`) VALUES (3,6,1,1,2,41,41,66,NULL,6,6,'{\"items\": [{\"field\": \"description\", \"index\": 0, \"reason\": \"明确全栈定位，覆盖JD核心关键词。\", \"status\": \"adopted\", \"section\": \"objective\", \"original\": null, \"optimized\": \"求职目标为全栈工程师/Java后端开发工程师，聚焦Spring Boot、Vue、MySQL、微服务架构与Web应用全生命周期开发，重点突出接口设计、前后端联调、SQL优化、高可用系统建设，并与产品、UI/UX协作推动高质量交付。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"补强学历与算法加分项。\", \"status\": \"adopted\", \"section\": \"education\", \"original\": \"学校/专业/学历/时间：[学校] · [专业] · [学历] · [起止时间]；主修课程：[课程]；荣誉奖项：[奖项]；若有深度学习、视觉算法或计算机相关项目，请补充项目名称、职责与成果。\", \"optimized\": \"[学校] · [专业] · [学历] · [起止时间]；主修[课程]，获得[奖项/荣誉]；参与[深度学习/视觉算法/计算机项目名称]，负责[职责]，使用[技术栈]完成[成果]，量化体现[指标提升X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"对齐职责要求，突出全栈与量化结果。\", \"status\": \"adopted\", \"section\": \"work\", \"original\": \"负责基于Java、Spring Boot、MySQL、Vue与微服务架构的Web功能开发，参与需求评审、接口设计、编码实现、联调自测及文档沉淀；配合产品与UI/UX完成前后端集成，优化SQL查询与公共组件，支撑 [X] 个模块上线，开发效率提升 [X%]，缺陷率下降 [X%]，接口问题定位效率提升 [X%]。\", \"optimized\": \"负责[业务场景]Web应用的全栈开发与交付，基于Java、Spring Boot、MySQL、Vue及微服务架构，参与需求评审、接口设计、数据库优化、前后端联调与文档沉淀；配合产品与UI/UX完成[X]个模块上线，开发效率提升[X%]，缺陷率下降[X%]，接口问题定位效率提升[X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"体现总师职责与端到端交付能力。\", \"status\": \"adopted\", \"section\": \"project\", \"original\": \"墨韵项目：围绕[业务场景]完成系统设计与功能实现，负责[前端页面/后端接口/数据库设计/联调测试]中的[具体职责]，使用[Java/Spring Boot/MySQL/Vue等真实技术]支撑[功能模块]交付，提升[业务指标/效率] [X%]，降低[问题率/成本] [X%]。\", \"optimized\": \"作为墨韵项目总设计师，围绕[业务场景]完成系统方案、模块拆分、数据库模型与接口规范设计；基于Java、Spring Boot、MySQL、Vue组织前后端开发、联调测试与上线验收，支撑[功能模块]交付，提升[业务指标][X%]，降低[问题率/成本][X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"分层展示技能，匹配全栈技术栈。\", \"status\": \"adopted\", \"section\": \"skills\", \"original\": \"Java(精通)、Spring Boot(精通)、MySQL(精通)、Vue(熟练)、HTML(熟练)、CSS(熟练)、JavaScript(熟练)、微服务架构(熟练)、SQL查询优化(精通)、接口设计(精通)、前后端联调(熟练)、代码文档沉淀(熟练)\", \"optimized\": \"精通：Java、Spring Boot、MySQL、SQL查询优化、REST接口设计、数据库模型设计\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、前后端联调、代码审查、技术文档沉淀\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈、高可用与协作能力。\", \"status\": \"adopted\", \"section\": \"selfIntro\", \"original\": \"具备[X]年Java Web全栈开发经验，熟悉Spring Boot、MySQL、Vue、HTML/CSS/JavaScript及微服务架构。能够参与架构设计、数据库优化、接口评审、代码审查与敏捷协作，推动前后端高质量交付；面对系统故障可定位瓶颈并优化可用性至[X%]。\", \"optimized\": \"具备[X]年Java Web全栈开发经验，熟悉Spring Boot、MySQL、Vue、HTML/CSS/JavaScript与微服务架构；能参与架构设计、数据库优化、接口评审、代码审查与敏捷协作，推动前后端高质量交付；擅长定位系统故障并优化可用性至[X%]。\"}], \"summary\": \"对齐全栈岗位，强化Java、Vue、MySQL、微服务与量化成果。\"}','2026-09-02 11:30:52');
INSERT INTO `portal_resume_optimize_history` (`id`, `user_id`, `resume_id`, `from_resume_id`, `job_target_id`, `score_before`, `score_after`, `match_score_before`, `match_score_after`, `adopted_count`, `total_count`, `optimize_data`, `create_time`) VALUES (4,6,1,1,2,41,41,66,NULL,6,6,'{\"items\": [{\"field\": \"description\", \"index\": 0, \"reason\": \"明确全栈定位，覆盖JD核心关键词。\", \"status\": \"adopted\", \"section\": \"objective\", \"original\": null, \"optimized\": \"求职目标为全栈工程师/Java后端开发工程师，聚焦Spring Boot、Vue、MySQL、微服务架构与Web应用全生命周期开发，重点突出接口设计、前后端联调、SQL优化、高可用系统建设，并与产品、UI/UX协作推动高质量交付。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"补强学历与算法加分项。\", \"status\": \"adopted\", \"section\": \"education\", \"original\": \"学校/专业/学历/时间：[学校] · [专业] · [学历] · [起止时间]；主修课程：[课程]；荣誉奖项：[奖项]；若有深度学习、视觉算法或计算机相关项目，请补充项目名称、职责与成果。\", \"optimized\": \"[学校] · [专业] · [学历] · [起止时间]；主修[课程]，获得[奖项/荣誉]；参与[深度学习/视觉算法/计算机项目名称]，负责[职责]，使用[技术栈]完成[成果]，量化体现[指标提升X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"对齐职责要求，突出全栈与量化结果。\", \"status\": \"adopted\", \"section\": \"work\", \"original\": \"负责基于Java、Spring Boot、MySQL、Vue与微服务架构的Web功能开发，参与需求评审、接口设计、编码实现、联调自测及文档沉淀；配合产品与UI/UX完成前后端集成，优化SQL查询与公共组件，支撑 [X] 个模块上线，开发效率提升 [X%]，缺陷率下降 [X%]，接口问题定位效率提升 [X%]。\", \"optimized\": \"负责[业务场景]Web应用的全栈开发与交付，基于Java、Spring Boot、MySQL、Vue及微服务架构，参与需求评审、接口设计、数据库优化、前后端联调与文档沉淀；配合产品与UI/UX完成[X]个模块上线，开发效率提升[X%]，缺陷率下降[X%]，接口问题定位效率提升[X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"体现总师职责与端到端交付能力。\", \"status\": \"adopted\", \"section\": \"project\", \"original\": \"墨韵项目：围绕[业务场景]完成系统设计与功能实现，负责[前端页面/后端接口/数据库设计/联调测试]中的[具体职责]，使用[Java/Spring Boot/MySQL/Vue等真实技术]支撑[功能模块]交付，提升[业务指标/效率] [X%]，降低[问题率/成本] [X%]。\", \"optimized\": \"作为墨韵项目总设计师，围绕[业务场景]完成系统方案、模块拆分、数据库模型与接口规范设计；基于Java、Spring Boot、MySQL、Vue组织前后端开发、联调测试与上线验收，支撑[功能模块]交付，提升[业务指标][X%]，降低[问题率/成本][X%]。\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"分层展示技能，匹配全栈技术栈。\", \"status\": \"adopted\", \"section\": \"skills\", \"original\": \"Java(精通)、Spring Boot(精通)、MySQL(精通)、Vue(熟练)、HTML(熟练)、CSS(熟练)、JavaScript(熟练)、微服务架构(熟练)、SQL查询优化(精通)、接口设计(精通)、前后端联调(熟练)、代码文档沉淀(熟练)\", \"optimized\": \"精通：Java、Spring Boot、MySQL、SQL查询优化、REST接口设计、数据库模型设计\\n熟练：Vue、HTML、CSS、JavaScript、微服务架构、前后端联调、代码审查、技术文档沉淀\"}, {\"field\": \"description\", \"index\": 0, \"reason\": \"突出全栈、高可用与协作能力。\", \"status\": \"adopted\", \"section\": \"selfIntro\", \"original\": \"具备[X]年Java Web全栈开发经验，熟悉Spring Boot、MySQL、Vue、HTML/CSS/JavaScript及微服务架构。能够参与架构设计、数据库优化、接口评审、代码审查与敏捷协作，推动前后端高质量交付；面对系统故障可定位瓶颈并优化可用性至[X%]。\", \"optimized\": \"具备[X]年Java Web全栈开发经验，熟悉Spring Boot、MySQL、Vue、HTML/CSS/JavaScript与微服务架构；能参与架构设计、数据库优化、接口评审、代码审查与敏捷协作，推动前后端高质量交付；擅长定位系统故障并优化可用性至[X%]。\"}], \"summary\": \"对齐全栈岗位，强化Java、Vue、MySQL、微服务与量化成果。\"}','2026-09-02 11:30:54');
/*!40000 ALTER TABLE `portal_resume_optimize_history` ENABLE KEYS */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

