/**
 * 图聚类算法
 * 使用 Louvain 社区发现算法自动识别节点分组
 */

import Graph from 'graphology'
import louvain from 'graphology-communities-louvain'

/**
 * 图聚类分析器
 */
export class GraphCluster {
  /**
   * 自动发现社区/分组
   * @param {Array} nodes - 节点列表
   * @param {Array} edges - 边列表
   * @param {Object} options - 选项
   * @returns {Array} - 自动生成的分组
   */
  static detectCommunities(nodes, edges, options = {}) {
    const {
      minGroupSize = 2,        // 最小分组大小
      resolution = 1.0,        // Louvain 分辨率参数
      generateLabels = true    // 是否生成分组标签
    } = options

    if (!nodes || nodes.length < 3 || !edges || edges.length < 2) {
      // 节点太少，不需要分组
      return []
    }

    try {
      const graph = new Graph()

      // 构建图
      const nodeIds = new Set()
      nodes.forEach(node => {
        if (!graph.hasNode(node.id)) {
          graph.addNode(node.id, { label: node.label })
          nodeIds.add(node.id)
        }
      })

      // 添加边（只添加有效边）
      edges.forEach(edge => {
        if (nodeIds.has(edge.from) && nodeIds.has(edge.to) && edge.from !== edge.to) {
          // 避免重复边
          if (!graph.hasEdge(edge.from, edge.to)) {
            graph.addEdge(edge.from, edge.to)
          }
        }
      })

      // 运行 Louvain 社区发现算法
      const communities = louvain(graph, { resolution })

      // 将社区转换为分组
      const groupMap = new Map()
      for (const [nodeId, communityId] of Object.entries(communities)) {
        if (!groupMap.has(communityId)) {
          groupMap.set(communityId, {
            id: `auto_group_${communityId}`,
            label: '',
            contains: [],
            style: 'container',
            autoGenerated: true
          })
        }
        groupMap.get(communityId).contains.push(nodeId)
      }

      // 过滤小分组并生成标签
      const groups = Array.from(groupMap.values())
        .filter(g => g.contains.length >= minGroupSize)
        .map((group, index) => {
          if (generateLabels) {
            group.label = this.generateGroupLabel(group.contains, nodes, index)
          }
          return group
        })

      console.log(`[GraphCluster] 发现 ${groups.length} 个社区分组`)
      return groups

    } catch (error) {
      console.warn('[GraphCluster] 社区发现失败:', error.message)
      return []
    }
  }

  /**
   * 生成分组标签
   * 基于组内节点的共同特征
   */
  static generateGroupLabel(nodeIds, allNodes, index) {
    const groupNodes = allNodes.filter(n => nodeIds.includes(n.id))
    
    // 策略1：查找共同的关键词
    const labels = groupNodes.map(n => (n.label || n.id).toLowerCase())
    const commonKeywords = this.findCommonKeywords(labels)
    
    if (commonKeywords.length > 0) {
      return commonKeywords[0] + ' 模块'
    }

    // 策略2：使用节点类型
    const icons = groupNodes.map(n => n.icon).filter(Boolean)
    if (icons.length > 0) {
      const iconCounts = {}
      icons.forEach(icon => {
        iconCounts[icon] = (iconCounts[icon] || 0) + 1
      })
      const dominantIcon = Object.entries(iconCounts)
        .sort((a, b) => b[1] - a[1])[0]?.[0]
      
      const iconLabels = {
        'database': '数据层',
        'cache': '缓存层',
        'server': '服务层',
        'queue': '消息队列',
        'actor': '用户层',
        'cloud': '云服务'
      }
      
      if (iconLabels[dominantIcon]) {
        return iconLabels[dominantIcon]
      }
    }

    // 策略3：使用默认标签
    return `模块 ${index + 1}`
  }

  /**
   * 查找共同关键词
   */
  static findCommonKeywords(labels) {
    const keywords = [
      { pattern: /user|用户|账户|account/i, label: '用户' },
      { pattern: /order|订单|purchase/i, label: '订单' },
      { pattern: /product|商品|item/i, label: '商品' },
      { pattern: /pay|支付|payment/i, label: '支付' },
      { pattern: /service|服务|svc/i, label: '服务' },
      { pattern: /data|数据|db|database/i, label: '数据' },
      { pattern: /api|gateway|网关/i, label: 'API' },
      { pattern: /cache|缓存|redis/i, label: '缓存' },
      { pattern: /queue|队列|mq|kafka/i, label: '消息' },
      { pattern: /auth|认证|login/i, label: '认证' },
      { pattern: /notification|通知|message/i, label: '通知' },
      { pattern: /search|搜索/i, label: '搜索' },
      { pattern: /file|文件|storage|存储/i, label: '存储' },
      { pattern: /log|日志|monitor|监控/i, label: '监控' }
    ]

    const found = []
    for (const { pattern, label } of keywords) {
      const matchCount = labels.filter(l => pattern.test(l)).length
      if (matchCount >= labels.length * 0.5) {
        found.push(label)
      }
    }

    return found
  }

  /**
   * 分析图的连通性
   * @returns {Object} - 连通性分析结果
   */
  static analyzeConnectivity(nodes, edges) {
    const nodeIds = new Set(nodes.map(n => n.id))
    const adjacency = new Map()
    
    // 构建邻接表
    nodes.forEach(n => adjacency.set(n.id, new Set()))
    
    edges.forEach(edge => {
      if (nodeIds.has(edge.from) && nodeIds.has(edge.to)) {
        adjacency.get(edge.from)?.add(edge.to)
        adjacency.get(edge.to)?.add(edge.from)
      }
    })

    // 计算度数
    const degrees = new Map()
    for (const [nodeId, neighbors] of adjacency) {
      degrees.set(nodeId, neighbors.size)
    }

    // 找出关键节点（度数最高的节点）
    const sortedByDegree = [...degrees.entries()]
      .sort((a, b) => b[1] - a[1])
    
    const hubNodes = sortedByDegree
      .slice(0, 3)
      .map(([id, degree]) => ({ id, degree }))

    // 找出孤立节点
    const isolatedNodes = [...degrees.entries()]
      .filter(([, degree]) => degree === 0)
      .map(([id]) => id)

    return {
      totalNodes: nodes.length,
      totalEdges: edges.length,
      averageDegree: edges.length * 2 / nodes.length,
      hubNodes,
      isolatedNodes,
      isConnected: isolatedNodes.length === 0
    }
  }

  /**
   * 基于层级的分组（适用于有 layer 属性的节点）
   */
  static groupByLayer(nodes) {
    const layers = new Map()
    
    nodes.forEach(node => {
      const layer = node.layer ?? -1
      if (!layers.has(layer)) {
        layers.set(layer, [])
      }
      layers.get(layer).push(node.id)
    })

    // 只为有明确层级的节点创建分组
    const groups = []
    const layerLabels = {
      0: '展示层',
      1: '网关层',
      2: '服务层',
      3: '数据层',
      4: '基础设施层'
    }

    for (const [layer, nodeIds] of layers) {
      if (layer >= 0 && nodeIds.length >= 2) {
        groups.push({
          id: `layer_group_${layer}`,
          label: layerLabels[layer] || `第 ${layer + 1} 层`,
          contains: nodeIds,
          style: 'region',
          autoGenerated: true
        })
      }
    }

    return groups
  }

  /**
   * 智能分组：结合社区发现和层级分组
   */
  static smartGrouping(nodes, edges, options = {}) {
    // 优先使用层级分组（只要有节点有 layer 属性）
    const nodesWithLayer = nodes.filter(n => n.layer !== undefined).length
    
    if (nodesWithLayer > 0) {
      const layerGroups = this.groupByLayer(nodes)
      if (layerGroups.length >= 1) {
        console.log('[GraphCluster] 使用层级分组策略，生成', layerGroups.length, '个层级')
        return layerGroups
      }
    }

    // 否则使用社区发现
    console.log('[GraphCluster] 使用社区发现策略')
    return this.detectCommunities(nodes, edges, options)
  }

  /**
   * 按层级分组节点
   */
  static groupByLayer(nodes) {
    const layerMap = new Map()
    
    // 收集每层的节点
    for (const node of nodes) {
      const layer = node.layer ?? 99
      if (!layerMap.has(layer)) {
        layerMap.set(layer, {
          id: `layer_${layer}`,
          label: this.getLayerLabel(layer, nodes.filter(n => (n.layer ?? 99) === layer)),
          contains: [],
          style: 'container',
          layer: layer
        })
      }
      layerMap.get(layer).contains.push(node.id)
    }
    
    // 按层级排序并返回
    return Array.from(layerMap.values())
      .sort((a, b) => a.layer - b.layer)
      .filter(g => g.contains.length > 0)
  }

  /**
   * 生成层级标签
   */
  static getLayerLabel(layer, layerNodes) {
    // 尝试从节点标签中推断层级名称
    const labels = layerNodes.map(n => n.label || '').filter(Boolean)
    const allText = labels.join(' ').toLowerCase()
    
    // 常见层级名称匹配（按优先级排序）
    const layerPatterns = [
      // 入口/客户端
      { pattern: /web|移动|app|小程序|客户端|终端|browser|ios|android/i, label: '接入终端' },
      { pattern: /cdn|负载|nginx|lb|loadbalance/i, label: '接入层' },
      // 网关
      { pattern: /网关|gateway|zuul|kong|apisix/i, label: 'API网关' },
      { pattern: /认证|auth|鉴权|oauth|jwt|sso/i, label: '认证授权' },
      // 服务
      { pattern: /用户|订单|商品|支付|库存|会员|账户/i, label: '业务服务' },
      { pattern: /服务|service|微服务|svc/i, label: '应用服务' },
      { pattern: /基础|公共|通用|common|工具|util/i, label: '基础服务' },
      // 中间件
      { pattern: /消息|mq|kafka|rabbit|rocketmq|队列/i, label: '消息中间件' },
      { pattern: /缓存|cache|redis|memcache/i, label: '缓存层' },
      { pattern: /搜索|elastic|es|solr/i, label: '搜索引擎' },
      // 存储
      { pattern: /数据库|mysql|postgres|oracle|mongodb|db/i, label: '数据存储' },
      { pattern: /文件|oss|s3|存储|storage|minio/i, label: '文件存储' },
      // 基础设施
      { pattern: /监控|日志|链路|trace|monitor|log/i, label: '监控日志' },
      { pattern: /部署|docker|k8s|kubernetes|容器/i, label: '容器平台' },
      { pattern: /云|aws|阿里云|腾讯云|azure/i, label: '云平台' }
    ]
    
    for (const { pattern, label } of layerPatterns) {
      if (pattern.test(allText)) {
        return label
      }
    }
    
    // 默认标签（按层级）
    const defaultLabels = ['接入层', '网关层', '服务层', '中间件层', '数据层', '基础设施']
    return defaultLabels[layer] || `第 ${layer + 1} 层`
  }
}
